### PR TITLE
fixes #28

### LINKED ISSUE #28: The api are broken
is a regression from the issue #24

### PR DESCRIPTION
**Pull request by NearTox**

### CODE REVIEW

File: functions/index.js [hunk 1]
```diff
@@ -51,6 +49,7 @@ app.get('/v1/dojo/auth/github/login', (req, res, next) => {
   });
 });
 
+app.use(mid.validateFirebaseIdToken)
```
Comment (NearTox) [inline functions/index.js:52]: this will be put after the endpoint of the login due the authenticator is not required for this method

File: functions/middleware.js [hunk 2]
```diff
@@ -5,8 +5,8 @@ functions.config()
 exports.validateFirebaseIdToken = (req, res, next) => {
 
   if ((!req.headers.authorization || !req.headers.authorization.startsWith('Bearer ')) &&
-      !req.cookies.__session) {
-    res.status(403, {"error":"Token no valid"});
```
Comment (NearTox) [inline functions/middleware.js:9]: the ``res.status(code, json)`` is a method that not exists so the express still waiting for the ``send()`` or the ``json()`` call
